name: pypi

on:
  release:
    types: [published]

jobs:

  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build dist
      run: make dist

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@7eb3b701d11256e583f5b49899c5e7203deab573
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
